title: The OCTAGON
author: Martins Bane
email: martinsbane@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  my journey into the tech world.. you are welcome to join me.

# social links
twitter_username: MartinsBane # DO NOT include the @ character, or else the build will fail!
github_username:  Martinsbane # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
